services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdi
    ports:
      - "5432:5432"
    volumes:
      - sdi_pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - sdi_redis:/data

volumes:
  sdi_pg:
  sdi_redis:
